name: Example 1
on: [push]
jobs:
    build:
      name: Build
      runs-on: self-hosted
      container: docker://dvcorg/cml:latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello
        run: |
          echo "Hello World from self hosted runner!"
